// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from configuration.djinni

#import <Foundation/Foundation.h>

extern NSString * __nonnull const LGAlgorandBlockchainExplorerEnginesALGORANDNODE;

@interface LGAlgorandBlockchainExplorerEngines : NSObject

@end
