// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from idl.djinni

#import "LGAlgorandAssetParams.h"
#import <Foundation/Foundation.h>

@interface LGAlgorandAssetConfigurationInfo : NSObject
- (nonnull instancetype)initWithAssetId:(nullable NSString *)assetId
                            assetParams:(nullable LGAlgorandAssetParams *)assetParams;
+ (nonnull instancetype)AlgorandAssetConfigurationInfoWithAssetId:(nullable NSString *)assetId
                                                      assetParams:(nullable LGAlgorandAssetParams *)assetParams;

/** The unique asset ID. Required to re-configure or destroy the asset, set to zero on asset creation. */
@property (nonatomic, readonly, nullable) NSString * assetId;

/** The asset configuration options. Empty when destroying the asset. */
@property (nonatomic, readonly, nullable) LGAlgorandAssetParams * assetParams;

@end
