// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from bitcoin_like_wallet.djinni

#import "LGBitcoinLikeSignature.h"


@implementation LGBitcoinLikeSignature

- (nonnull instancetype)initWithR:(nonnull NSData *)r
                                s:(nonnull NSData *)s
                                v:(nonnull NSData *)v
{
    if (self = [super init]) {
        _r = [r copy];
        _s = [s copy];
        _v = [v copy];
    }
    return self;
}

+ (nonnull instancetype)BitcoinLikeSignatureWithR:(nonnull NSData *)r
                                                s:(nonnull NSData *)s
                                                v:(nonnull NSData *)v
{
    return [[self alloc] initWithR:r
                                 s:s
                                 v:v];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p r:%@ s:%@ v:%@>", self.class, (void *)self, self.r, self.s, self.v];
}

@end
