// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from configuration.djinni

#import <Foundation/Foundation.h>

extern NSString * __nonnull const LGBlockchainObserverEnginesLEDGERAPI;

/** Available API to use with observers. */
@interface LGBlockchainObserverEngines : NSObject

@end
