// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from configuration.djinni

#import "LGBlockchainObserverEngines.h"


NSString * __nonnull const LGBlockchainObserverEnginesSTARGATENODE = @"STARGATE_NODE";

NSString * __nonnull const LGBlockchainObserverEnginesCOSMOSNODE = @"COSMOS_NODE";

NSString * __nonnull const LGBlockchainObserverEnginesLEDGERAPI = @"LEDGER_API";

NSString * __nonnull const LGBlockchainObserverEnginesRIPPLENODE = @"RIPPLE_NODE";

NSString * __nonnull const LGBlockchainObserverEnginesTEZOSNODE = @"TEZOS_NODE";
