// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#import "LGCosmosLikeMsgDelegate.h"


@implementation LGCosmosLikeMsgDelegate

- (nonnull instancetype)initWithDelegatorAddress:(nonnull NSString *)delegatorAddress
                                validatorAddress:(nonnull NSString *)validatorAddress
                                          amount:(nonnull LGCosmosLikeAmount *)amount
{
    if (self = [super init]) {
        _delegatorAddress = [delegatorAddress copy];
        _validatorAddress = [validatorAddress copy];
        _amount = amount;
    }
    return self;
}

+ (nonnull instancetype)CosmosLikeMsgDelegateWithDelegatorAddress:(nonnull NSString *)delegatorAddress
                                                 validatorAddress:(nonnull NSString *)validatorAddress
                                                           amount:(nonnull LGCosmosLikeAmount *)amount
{
    return [[self alloc] initWithDelegatorAddress:delegatorAddress
                                 validatorAddress:validatorAddress
                                           amount:amount];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p delegatorAddress:%@ validatorAddress:%@ amount:%@>", self.class, (void *)self, self.delegatorAddress, self.validatorAddress, self.amount];
}

@end
