// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from validators.djinni

#import <Foundation/Foundation.h>

/** Human readable description of validators */
@interface LGCosmosLikeValidatorDescription : NSObject
- (nonnull instancetype)initWithMoniker:(nonnull NSString *)moniker
                               identity:(nullable NSString *)identity
                                website:(nullable NSString *)website
                                details:(nullable NSString *)details;
+ (nonnull instancetype)CosmosLikeValidatorDescriptionWithMoniker:(nonnull NSString *)moniker
                                                         identity:(nullable NSString *)identity
                                                          website:(nullable NSString *)website
                                                          details:(nullable NSString *)details;

@property (nonatomic, readonly, nonnull) NSString * moniker;

@property (nonatomic, readonly, nullable) NSString * identity;

@property (nonatomic, readonly, nullable) NSString * website;

@property (nonatomic, readonly, nullable) NSString * details;

@end
