// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wallet.djinni

#import "LGCosmosConfigurationDefaults.h"


NSString * __nonnull const LGCosmosConfigurationDefaultsCOSMOSDEFAULTAPIENDPOINT = @"https://cosmoshub4.coin.ledger.com";

NSString * __nonnull const LGCosmosConfigurationDefaultsCOSMOSOBSERVERWSENDPOINT = @"";
