// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#import "LGCosmosLikeAmount.h"
#import <Foundation/Foundation.h>

@interface LGCosmosLikeMsgBeginRedelegate : NSObject
- (nonnull instancetype)initWithDelegatorAddress:(nonnull NSString *)delegatorAddress
                          validatorSourceAddress:(nonnull NSString *)validatorSourceAddress
                     validatorDestinationAddress:(nonnull NSString *)validatorDestinationAddress
                                          amount:(nonnull LGCosmosLikeAmount *)amount;
+ (nonnull instancetype)CosmosLikeMsgBeginRedelegateWithDelegatorAddress:(nonnull NSString *)delegatorAddress
                                                  validatorSourceAddress:(nonnull NSString *)validatorSourceAddress
                                             validatorDestinationAddress:(nonnull NSString *)validatorDestinationAddress
                                                                  amount:(nonnull LGCosmosLikeAmount *)amount;

@property (nonatomic, readonly, nonnull) NSString * delegatorAddress;

@property (nonatomic, readonly, nonnull) NSString * validatorSourceAddress;

@property (nonatomic, readonly, nonnull) NSString * validatorDestinationAddress;

@property (nonatomic, readonly, nonnull) LGCosmosLikeAmount * amount;

@end
