// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#import "LGCosmosLikeMsgSend.h"


@implementation LGCosmosLikeMsgSend

- (nonnull instancetype)initWithFromAddress:(nonnull NSString *)fromAddress
                                  toAddress:(nonnull NSString *)toAddress
                                     amount:(nonnull NSArray<LGCosmosLikeAmount *> *)amount
{
    if (self = [super init]) {
        _fromAddress = [fromAddress copy];
        _toAddress = [toAddress copy];
        _amount = [amount copy];
    }
    return self;
}

+ (nonnull instancetype)CosmosLikeMsgSendWithFromAddress:(nonnull NSString *)fromAddress
                                               toAddress:(nonnull NSString *)toAddress
                                                  amount:(nonnull NSArray<LGCosmosLikeAmount *> *)amount
{
    return [[self alloc] initWithFromAddress:fromAddress
                                   toAddress:toAddress
                                      amount:amount];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p fromAddress:%@ toAddress:%@ amount:%@>", self.class, (void *)self, self.fromAddress, self.toAddress, self.amount];
}

@end
