// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from validators.djinni

#import "LGCosmosLikeValidator.h"


@implementation LGCosmosLikeValidator

- (nonnull instancetype)initWithValidatorDetails:(nonnull LGCosmosLikeValidatorDescription *)validatorDetails
                                      commission:(nonnull LGCosmosLikeValidatorCommission *)commission
                                        distInfo:(nonnull LGCosmosLikeValidatorDistributionInformation *)distInfo
                                        signInfo:(nonnull LGCosmosLikeValidatorSigningInformation *)signInfo
                                 unbondingHeight:(int32_t)unbondingHeight
                                   unbondingTime:(nullable NSDate *)unbondingTime
                               minSelfDelegation:(nonnull NSString *)minSelfDelegation
                                          jailed:(BOOL)jailed
                                     votingPower:(nonnull NSString *)votingPower
                                 operatorAddress:(nonnull NSString *)operatorAddress
                                 consensusPubkey:(nonnull NSString *)consensusPubkey
                                    activeStatus:(int32_t)activeStatus
{
    if (self = [super init]) {
        _validatorDetails = validatorDetails;
        _commission = commission;
        _distInfo = distInfo;
        _signInfo = signInfo;
        _unbondingHeight = unbondingHeight;
        _unbondingTime = unbondingTime;
        _minSelfDelegation = [minSelfDelegation copy];
        _jailed = jailed;
        _votingPower = [votingPower copy];
        _operatorAddress = [operatorAddress copy];
        _consensusPubkey = [consensusPubkey copy];
        _activeStatus = activeStatus;
    }
    return self;
}

+ (nonnull instancetype)CosmosLikeValidatorWithValidatorDetails:(nonnull LGCosmosLikeValidatorDescription *)validatorDetails
                                                     commission:(nonnull LGCosmosLikeValidatorCommission *)commission
                                                       distInfo:(nonnull LGCosmosLikeValidatorDistributionInformation *)distInfo
                                                       signInfo:(nonnull LGCosmosLikeValidatorSigningInformation *)signInfo
                                                unbondingHeight:(int32_t)unbondingHeight
                                                  unbondingTime:(nullable NSDate *)unbondingTime
                                              minSelfDelegation:(nonnull NSString *)minSelfDelegation
                                                         jailed:(BOOL)jailed
                                                    votingPower:(nonnull NSString *)votingPower
                                                operatorAddress:(nonnull NSString *)operatorAddress
                                                consensusPubkey:(nonnull NSString *)consensusPubkey
                                                   activeStatus:(int32_t)activeStatus
{
    return [[self alloc] initWithValidatorDetails:validatorDetails
                                       commission:commission
                                         distInfo:distInfo
                                         signInfo:signInfo
                                  unbondingHeight:unbondingHeight
                                    unbondingTime:unbondingTime
                                minSelfDelegation:minSelfDelegation
                                           jailed:jailed
                                      votingPower:votingPower
                                  operatorAddress:operatorAddress
                                  consensusPubkey:consensusPubkey
                                     activeStatus:activeStatus];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p validatorDetails:%@ commission:%@ distInfo:%@ signInfo:%@ unbondingHeight:%@ unbondingTime:%@ minSelfDelegation:%@ jailed:%@ votingPower:%@ operatorAddress:%@ consensusPubkey:%@ activeStatus:%@>", self.class, (void *)self, self.validatorDetails, self.commission, self.distInfo, self.signInfo, @(self.unbondingHeight), self.unbondingTime, self.minSelfDelegation, @(self.jailed), self.votingPower, self.operatorAddress, self.consensusPubkey, @(self.activeStatus)];
}

@end
