// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wallet.djinni

#import <Foundation/Foundation.h>


/** A cosmos-like wallet. */
@interface LGCosmosLikeWallet : NSObject

@end
