// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from validators.djinni

#import "LGCosmosLikeCommissionRates.h"
#import <Foundation/Foundation.h>

/** Commission data for a Validator */
@interface LGCosmosLikeValidatorCommission : NSObject
- (nonnull instancetype)initWithRates:(nonnull LGCosmosLikeCommissionRates *)rates
                           updateTime:(nonnull NSDate *)updateTime;
+ (nonnull instancetype)CosmosLikeValidatorCommissionWithRates:(nonnull LGCosmosLikeCommissionRates *)rates
                                                    updateTime:(nonnull NSDate *)updateTime;

@property (nonatomic, readonly, nonnull) LGCosmosLikeCommissionRates * rates;

@property (nonatomic, readonly, nonnull) NSDate * updateTime;

@end
