// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#import <Foundation/Foundation.h>

/** Probably deprecated and replaced by MsgWithdrawDelegatIONReward */
@interface LGCosmosLikeMsgWithdrawDelegatorReward : NSObject
- (nonnull instancetype)initWithDelegatorAddress:(nonnull NSString *)delegatorAddress
                                validatorAddress:(nonnull NSString *)validatorAddress;
+ (nonnull instancetype)CosmosLikeMsgWithdrawDelegatorRewardWithDelegatorAddress:(nonnull NSString *)delegatorAddress
                                                                validatorAddress:(nonnull NSString *)validatorAddress;

@property (nonatomic, readonly, nonnull) NSString * delegatorAddress;

@property (nonatomic, readonly, nonnull) NSString * validatorAddress;

@end
