// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from dynamic.djinni

#import "LGDynamicType.h"
#import <Foundation/Foundation.h>
@class LGDynamicArray;
@class LGDynamicObject;


/** A collection of dynamic values in an array. Values can be retrieved via their indexes. */
@interface LGDynamicArray : NSObject

/**
 * Get count of values.
 * @return 64-bit integer
 */
- (int64_t)size;

/**
 * Push a 32-bit integer.
 * @param value, 32-bit integer
 * @return DynamicArray with value stored in it
 */
- (nullable LGDynamicArray *)pushInt:(int32_t)value;

/**
 * Push a 64-bit integer.
 * @param value, 64-bit integer
 * @return DynamicArray with value stored in it
 */
- (nullable LGDynamicArray *)pushLong:(int64_t)value;

/**
 * Push a string.
 * @param value, string
 * @return DynamicArray with value stored in it
 */
- (nullable LGDynamicArray *)pushString:(nonnull NSString *)value;

/**
 * Push a double.
 * @param value, double
 * @return DynamicArray with value stored in it
 */
- (nullable LGDynamicArray *)pushDouble:(double)value;

/**
 * Push a binary.
 * @param value, binary
 * @return DynamicArray with value stored in it
 */
- (nullable LGDynamicArray *)pushData:(nonnull NSData *)value;

/**
 * Push a bool.
 * @param value, bool
 * @return DynamicArray with value stored in it
 */
- (nullable LGDynamicArray *)pushBoolean:(BOOL)value;

/**
 * Push a dynamic object.
 * @param value, DynamicObject
 * @return DynamicArray with value stored in it
 */
- (nullable LGDynamicArray *)pushObject:(nullable LGDynamicObject *)value;

/**
 * Push a dynamic array.
 * @param value, DynamicArray
 * @return DynamicArray with value stored in it
 */
- (nullable LGDynamicArray *)pushArray:(nullable LGDynamicArray *)value;

/**
 * Get a string at a given index.
 * @param index, 64-bit integer
 * @return Optional string
 */
- (nullable NSString *)getString:(int64_t)index;

/**
 * Get 32-bit integer at a given index.
 * @param index, 64-bit integer
 * @return Optional 32-bit integer
 */
- (nullable NSNumber *)getInt:(int64_t)index;

/**
 * Get 64-bit integer at a given index.
 * @param index, 64-bit integer
 * @return Optional 64-bit integer
 */
- (nullable NSNumber *)getLong:(int64_t)index;

/**
 * Get double at a given index.
 * @param index, 64-bit integer
 * @return Optional double
 */
- (nullable NSNumber *)getDouble:(int64_t)index;

/**
 * Get binary at a given index.
 * @param index, 64-bit integer
 * @return Optional binary
 */
- (nullable NSData *)getData:(int64_t)index;

/**
 * Get bool at a given index.
 * @param index, 64-bit integer
 * @return Optional bool
 */
- (nullable NSNumber *)getBoolean:(int64_t)index;

/**
 * Get DynamicObject object at a given index.
 * @param index, 64-bit integer
 * @return Optional DynamicObject
 */
- (nullable LGDynamicObject *)getObject:(int64_t)index;

/**
 * Get DynamicArray object at a given index.
 * @param index, 64-bit integer
 * @return Optional DynamicArray
 */
- (nullable LGDynamicArray *)getArray:(int64_t)index;

/**
 * Concatenate current DynamicArray with another one.
 * @param array, DynamicArray object to concatenate with
 * @return DynamicArray object, concatenated DynamicArray
 */
- (nullable LGDynamicArray *)concat:(nullable LGDynamicArray *)array;

/**
 * Get type of value stored at a given index.
 * @param index, 64 bits integer
 * @return Optional DynamicType enum entry
 */
- (nullable NSNumber *)getType:(int64_t)index;

/**
 * Delete value stored at given index.
 * @param index, 64 bits integer
 * @return bool, true if deletion succeeded
 */
- (BOOL)remove:(int64_t)index;

/**
 * Dump whole object's content as string.
 * @return string, the string representation of the array
 */
- (nonnull NSString *)dump;

/**
 * Serialize whole object to a binary.
 * @return binary, the serialized array
 */
- (nonnull NSData *)serialize;

/**
 * Get readonly status of object.
 * @return bool, whether the array is in read-only mode
 */
- (BOOL)isReadOnly;

/**
 * Create a new instance of DynamicArray class.
 * @return DynamicArray, a brand new instance of a dynamic array
 */
+ (nullable LGDynamicArray *)newInstance;

/**
 * Parse a binary to a DynamicArray.
 * @param serialized, binary to parse
 * @return Optional, the unserialized dynamic array
 */
+ (nullable LGDynamicArray *)load:(nonnull NSData *)serialized;

@end
