// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from erc20.djinni

#import "LGOperationType.h"
#import <Foundation/Foundation.h>
@class LGBigInt;


/** Class representing a Ethereum transaction. */
@interface LGERC20LikeOperation : NSObject

/** Get the hash of the transaction. */
- (nonnull NSString *)getHash;

/** Get the nonce of the transaction : sequence number issued by originating EOA. */
- (nullable LGBigInt *)getNonce;

/** Get Gas price (in wei). */
- (nullable LGBigInt *)getGasPrice;

/** Get start gas (in wei) : maximum amount of gas the originator is willing to pay. */
- (nullable LGBigInt *)getGasLimit;

/** Used gas (in wei) : used gas during this transaction: */
- (nullable LGBigInt *)getUsedGas;

/** Get source ETH address. */
- (nonnull NSString *)getSender;

/** Get destination ETH address. */
- (nonnull NSString *)getReceiver;

/** Get amount of ether to send. */
- (nullable LGBigInt *)getValue;

/** Get binary data payload. */
- (nonnull NSData *)getData;

/**
 * Get the time when the transaction was issued or the time of the block including this
 * this transaction.
 */
- (nonnull NSDate *)getTime;

/** Get operation type : whether it is a SEND or RECEIVE. */
- (LGOperationType)getOperationType;

/** Get opration status : pending or confirmed. */
- (int32_t)getStatus;

@end
