// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ethereum_like_wallet.djinni

#import <Foundation/Foundation.h>
@class LGERC20LikeAccount;
@class LGEthereumLikeTransaction;
@class LGEthereumLikeTransactionBuilder;
@protocol LGBigIntCallback;
@protocol LGStringCallback;


/** Class representing a Ethereum account. */
@interface LGEthereumLikeAccount : NSObject

/** Send a raw (binary) transaction on the Ethereum blockchain. */
- (void)broadcastRawTransaction:(nonnull NSData *)transaction
                       callback:(nullable id<LGStringCallback>)callback;

/** Send a transaction on the Ethereum blockchain. */
- (void)broadcastTransaction:(nullable LGEthereumLikeTransaction *)transaction
                    callback:(nullable id<LGStringCallback>)callback;

/** Get a builder object to construct transactions. */
- (nullable LGEthereumLikeTransactionBuilder *)buildTransaction;

/** Get the list of ERC20 accounts associated with this Ethereum account. */
- (nonnull NSArray<LGERC20LikeAccount *> *)getERC20Accounts;

/**
 * Get gas price from network
 * Note: same note as for getFees method on BitcoinLikeAccount
 */
- (void)getGasPrice:(nullable id<LGBigIntCallback>)callback;

/**
 * Get estimated gas limit to set so the transaction will succeed
 * The passed address could be EOA or contract
 * This estimation is based on X last incoming txs (to address) that succeeded
 * Note: same note as for getFees method on BitcoinLikeAccount
 */
- (void)getEstimatedGasLimit:(nonnull NSString *)address
                    callback:(nullable id<LGBigIntCallback>)callback;

@end
