// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ethereum_like_wallet.djinni

#import "LGEthereumGasLimitRequest.h"
#import <Foundation/Foundation.h>
@class LGERC20LikeAccount;
@class LGEthereumLikeTransaction;
@class LGEthereumLikeTransactionBuilder;
@protocol LGBigIntCallback;
@protocol LGBigIntListCallback;
@protocol LGStringCallback;


/** Class representing a Ethereum account. */
@interface LGEthereumLikeAccount : NSObject

/** Send a raw (binary) transaction on the Ethereum blockchain. */
- (void)broadcastRawTransaction:(nonnull NSData *)transaction
                       callback:(nullable id<LGStringCallback>)callback;

/** Send a transaction on the Ethereum blockchain. */
- (void)broadcastTransaction:(nullable LGEthereumLikeTransaction *)transaction
                    callback:(nullable id<LGStringCallback>)callback;

/** Get a builder object to construct transactions. */
- (nullable LGEthereumLikeTransactionBuilder *)buildTransaction;

/** Get the list of ERC20 accounts associated with this Ethereum account. */
- (nonnull NSArray<LGERC20LikeAccount *> *)getERC20Accounts;

/**
 * Get gas price from network
 * Note: it would have been better to have this method on EthereumLikeWallet
 * but since EthereumLikeWallet is not used anywhere, it's better to keep all
 * specific methods under the same specific class so it will be easy to segratate
 * when the right time comes !
 */
- (void)getGasPrice:(nullable id<LGBigIntCallback>)callback;

/**
 * Get estimated gas limit to set so the transaction will succeed
 * The passed address could be EOA or contract
 * This estimation is based on X last incoming txs (to address) that succeeded
 * Note: same note as above
 */
- (void)getEstimatedGasLimit:(nonnull NSString *)address
                    callback:(nullable id<LGBigIntCallback>)callback;

/**
 * Get estimated gas limit to set so the transaction will succeed
 * The passed address could be EOA or contract
 * This estimation is based on a dry-run on the node, and it will fail if the request is ill-formed
 * Note: same note as above
 */
- (void)getDryRunGasLimit:(nonnull NSString *)address
                  request:(nonnull LGEthereumGasLimitRequest *)request
                 callback:(nullable id<LGBigIntCallback>)callback;

/**
 * Get balance of ERC20 token
 * The passed address is an ERC20 account
 * Note: same note as above
 */
- (void)getERC20Balance:(nonnull NSString *)erc20Address
               callback:(nullable id<LGBigIntCallback>)callback;

/**
 * Get balance of ERC20 tokens
 * The passed addresses are ERC20 accounts
 * Note: same note as above
 */
- (void)getERC20Balances:(nonnull NSArray<NSString *> *)erc20Addresses
                callback:(nullable id<LGBigIntListCallback>)callback;

/**
 * Add ERC20 accounts
 * The passed addresses are ERC20 accounts
 * Note: same note as above
 */
- (void)addERC20Accounts:(nonnull NSArray<NSString *> *)erc20Addresses;

@end
