// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wallet.djinni

#import <Foundation/Foundation.h>

/**
 * Type of operation.
 *
 * It’s possible to either send funds or receive ones.
 */
typedef NS_ENUM(NSInteger, LGOperationType)
{
    LGOperationTypeSend,
    LGOperationTypeReceive,
    LGOperationTypeNone,
};
