// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ripple_like_wallet.djinni

#import <Foundation/Foundation.h>
@class LGRippleLikeTransaction;
@class LGRippleLikeTransactionBuilder;
@protocol LGStringCallback;


/**Class representing a Ripple account */
@interface LGRippleLikeAccount : NSObject

- (void)broadcastRawTransaction:(nonnull NSData *)transaction
                       callback:(nullable id<LGStringCallback>)callback;

- (void)broadcastTransaction:(nullable LGRippleLikeTransaction *)transaction
                    callback:(nullable id<LGStringCallback>)callback;

- (nullable LGRippleLikeTransactionBuilder *)buildTransaction;

@end
