// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ripple_like_wallet.djinni

#import <Foundation/Foundation.h>
@class LGRippleLikeTransaction;
@class LGRippleLikeTransactionBuilder;
@protocol LGAmountCallback;
@protocol LGBoolCallback;
@protocol LGStringCallback;


/**Class representing a Ripple account */
@interface LGRippleLikeAccount : NSObject

- (void)broadcastRawTransaction:(nonnull NSData *)transaction
                       callback:(nullable id<LGStringCallback>)callback;

- (void)broadcastTransaction:(nullable LGRippleLikeTransaction *)transaction
                    callback:(nullable id<LGStringCallback>)callback;

- (nullable LGRippleLikeTransactionBuilder *)buildTransaction;

/**
 * Get fees from network
 * Note: it would have been better to have this method on RippleLikeWallet
 * but since RippleLikeWallet is not used anywhere, it's better to keep all
 * specific methods under the same specific class so it will be easy to segratate
 * when the right time comes !
 */
- (void)getFees:(nullable id<LGAmountCallback>)callback;

/**
 * Get base reserve (dust to leave on an XRP account) from network
 * Note: same note as above
 */
- (void)getBaseReserve:(nullable id<LGAmountCallback>)callback;

/**
 * Check whether an account has been activated or not
 * Here activation, means that the XRP account received a first transaction with a minimum amount
 * greater or equal to XRP base reserve
 * @param: address to check
 * @return: true if valid address and has been activated, false otherwise
 */
- (void)isAddressActivated:(nonnull NSString *)address
               isActivated:(nullable id<LGBoolCallback>)isActivated;

@end
