// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ripple_like_wallet.djinni

#import <Foundation/Foundation.h>

extern NSString * __nonnull const LGRippleConfigurationRIPPLELASTLEDGERSEQUENCEOFFSET;

@interface LGRippleConfiguration : NSObject

@end
