// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from stellar_like_wallet.djinni

#import <Foundation/Foundation.h>

@interface LGStellarLikeAccountSigner : NSObject
- (nonnull instancetype)initWithKey:(nonnull NSString *)key
                               type:(nonnull NSString *)type
                             weight:(int32_t)weight;
+ (nonnull instancetype)StellarLikeAccountSignerWithKey:(nonnull NSString *)key
                                                   type:(nonnull NSString *)type
                                                 weight:(int32_t)weight;

@property (nonatomic, readonly, nonnull) NSString * key;

@property (nonatomic, readonly, nonnull) NSString * type;

@property (nonatomic, readonly) int32_t weight;

@end
