// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from tezos_like_wallet.djinni

#import "LGTezosOperationTag.h"
#import <Foundation/Foundation.h>
@class LGAmount;
@class LGBigInt;
@class LGTezosLikeAddress;


/**Class representing a Tezos transaction */
@interface LGTezosLikeTransaction : NSObject

/** Get type of operation (transaction, reveal ... cf TezosOperationTag) */
- (LGTezosOperationTag)getType;

/** Get the hash of the transaction. */
- (nonnull NSString *)getHash;

/** Get Fees (in drop) */
- (nullable LGAmount *)getFees;

/** Get destination XTZ. address */
- (nullable LGTezosLikeAddress *)getReceiver;

/** Get XTZ. sender address */
- (nullable LGTezosLikeAddress *)getSender;

/** Get amount of XTZ to send */
- (nullable LGAmount *)getValue;

/** Serialize the transaction to its raw format. */
- (nonnull NSData *)serialize;

/** Set signature of transaction, when a signature is set serialize method gives back serialized Tx */
- (void)setSignature:(nonnull NSData *)signature;

/**
 * Get the time when the transaction was issued or the time of the block including
 * this transaction
 */
- (nonnull NSDate *)getDate;

/** Get Signing public Key */
- (nonnull NSData *)getSigningPubKey;

- (nullable LGBigInt *)getCounter;

- (nullable LGAmount *)getGasLimit;

- (nullable LGBigInt *)getStorageLimit;

/** Get hash of block in which tx is included */
- (nullable NSString *)getBlockHash;

@end
