// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from idl.djinni

#ifndef DJINNI_GENERATED_ALGORANDWALLET_HPP
#define DJINNI_GENERATED_ALGORANDWALLET_HPP

namespace ledger { namespace core { namespace api {

class AlgorandWallet {
public:
    virtual ~AlgorandWallet() {}
};

} } }  // namespace ledger::core::api
#endif //DJINNI_GENERATED_ALGORANDWALLET_HPP
