// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from database.djinni

#ifndef DJINNI_GENERATED_DATABASEBACKENDTYPE_HPP
#define DJINNI_GENERATED_DATABASEBACKENDTYPE_HPP

#include <functional>
#include <iostream>
#include <string>

namespace ledger { namespace core { namespace api {

enum class DatabaseBackendType : int {
    SQLITE3,
    POSTGRESQL,
};
 std::string to_string(const DatabaseBackendType& databaseBackendType);
 std::ostream &operator<<(std::ostream &os, const DatabaseBackendType &o);

} } }  // namespace ledger::core::api

namespace std {

template <>
struct hash<::ledger::core::api::DatabaseBackendType> {
    size_t operator()(::ledger::core::api::DatabaseBackendType type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
#endif //DJINNI_GENERATED_DATABASEBACKENDTYPE_HPP
