// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ethereum_like_wallet.djinni

package com.ledger.reactnative;

import co.ledger.core.EthereumGasLimitRequest;
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.bridge.ReadableArray;
import com.facebook.react.bridge.ReadableMap;
import com.facebook.react.bridge.ReadableNativeArray;
import com.facebook.react.bridge.ReadableNativeMap;
import com.facebook.react.bridge.WritableNativeArray;
import com.facebook.react.bridge.WritableNativeMap;
import com.facebook.react.module.annotations.ReactModule;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Optional;
import java.util.TimeZone;
import java.util.UUID;

/** Class representing a GasLimit request for the Eth explorers */
@ReactModule(name = "RCTCoreEthereumGasLimitRequest")
public class RCTCoreEthereumGasLimitRequest extends ReactContextBaseJavaModule {
    private final ReactApplicationContext reactContext;
    private Map<String, EthereumGasLimitRequest> javaObjects;
    public Map<String, EthereumGasLimitRequest> getJavaObjects()
    {
        return javaObjects;
    }

    public RCTCoreEthereumGasLimitRequest(ReactApplicationContext reactContext)
    {
        super(reactContext);
        this.reactContext = reactContext;
        this.javaObjects = new HashMap<String, EthereumGasLimitRequest>();
    }

    @Override
    public String getName()
    {
        return "RCTCoreEthereumGasLimitRequest";
    }
    @ReactMethod
    public void release(ReadableMap currentInstance, Promise promise)
    {
        String uid = currentInstance.getString("uid");
        if (uid.length() > 0)
        {
            this.javaObjects.remove(uid);
            promise.resolve(0);
        }
        else
        {
            promise.reject("Failed to release instance of RCTCoreEthereumGasLimitRequest", "First parameter of RCTCoreEthereumGasLimitRequest::release should be an instance of RCTCoreEthereumGasLimitRequest");
        }
    }
    @ReactMethod
    public void log(Promise promise)
    {
        WritableNativeArray result = new WritableNativeArray();
        for (Map.Entry<String, EthereumGasLimitRequest> elem : this.javaObjects.entrySet())
        {
            result.pushString(elem.getKey());
        }
        promise.resolve(result);
    }
    @ReactMethod
    public void flush(Promise promise)
    {
        this.javaObjects.clear();
        promise.resolve(0);
    }
    @ReactMethod
    public void isNull(ReadableMap currentInstance, Promise promise)
    {
        String uid = currentInstance.getString("uid");
        if (uid.length() > 0)
        {
            if (this.javaObjects.get(uid) == null)
            {
                promise.resolve(true);
                return;
            }
            else
            {
                promise.resolve(false);
                return;
            }
        }
        promise.resolve(true);
    }

    @ReactMethod
    public void init(String from, String to, String value, String data, String gas, String gasPrice, String amplifier, Promise promise) {
        EthereumGasLimitRequest javaResult = new EthereumGasLimitRequest(from, to, value, data, gas, gasPrice, amplifier);

        String uuid = UUID.randomUUID().toString();
        this.javaObjects.put(uuid, javaResult);
        WritableNativeMap finalResult = new WritableNativeMap();
        finalResult.putString("type","RCTCoreEthereumGasLimitRequest");
        finalResult.putString("uid",uuid);
        promise.resolve(finalResult);
    }
    @ReactMethod
    public void getFrom(ReadableMap currentInstance, Promise promise)
    {
        String uid = currentInstance.getString("uid");
        if (uid.length() > 0)
        {
            EthereumGasLimitRequest javaObj = this.javaObjects.get(uid);
            String result = javaObj.getFrom();
            WritableNativeMap resultMap = new WritableNativeMap();
            resultMap.putString("value", result);
            promise.resolve(resultMap);
        }
        else
        {
            promise.reject("Failed to call RCTCoreEthereumGasLimitRequest::getFrom", "First parameter of RCTCoreEthereumGasLimitRequest::getFrom should be an instance of RCTCoreEthereumGasLimitRequest");
        }
    }

    @ReactMethod
    public void getTo(ReadableMap currentInstance, Promise promise)
    {
        String uid = currentInstance.getString("uid");
        if (uid.length() > 0)
        {
            EthereumGasLimitRequest javaObj = this.javaObjects.get(uid);
            String result = javaObj.getTo();
            WritableNativeMap resultMap = new WritableNativeMap();
            resultMap.putString("value", result);
            promise.resolve(resultMap);
        }
        else
        {
            promise.reject("Failed to call RCTCoreEthereumGasLimitRequest::getTo", "First parameter of RCTCoreEthereumGasLimitRequest::getTo should be an instance of RCTCoreEthereumGasLimitRequest");
        }
    }

    @ReactMethod
    public void getValue(ReadableMap currentInstance, Promise promise)
    {
        String uid = currentInstance.getString("uid");
        if (uid.length() > 0)
        {
            EthereumGasLimitRequest javaObj = this.javaObjects.get(uid);
            String result = javaObj.getValue();
            WritableNativeMap resultMap = new WritableNativeMap();
            resultMap.putString("value", result);
            promise.resolve(resultMap);
        }
        else
        {
            promise.reject("Failed to call RCTCoreEthereumGasLimitRequest::getValue", "First parameter of RCTCoreEthereumGasLimitRequest::getValue should be an instance of RCTCoreEthereumGasLimitRequest");
        }
    }

    @ReactMethod
    public void getData(ReadableMap currentInstance, Promise promise)
    {
        String uid = currentInstance.getString("uid");
        if (uid.length() > 0)
        {
            EthereumGasLimitRequest javaObj = this.javaObjects.get(uid);
            String result = javaObj.getData();
            WritableNativeMap resultMap = new WritableNativeMap();
            resultMap.putString("value", result);
            promise.resolve(resultMap);
        }
        else
        {
            promise.reject("Failed to call RCTCoreEthereumGasLimitRequest::getData", "First parameter of RCTCoreEthereumGasLimitRequest::getData should be an instance of RCTCoreEthereumGasLimitRequest");
        }
    }

    @ReactMethod
    public void getGas(ReadableMap currentInstance, Promise promise)
    {
        String uid = currentInstance.getString("uid");
        if (uid.length() > 0)
        {
            EthereumGasLimitRequest javaObj = this.javaObjects.get(uid);
            String result = javaObj.getGas();
            WritableNativeMap resultMap = new WritableNativeMap();
            resultMap.putString("value", result);
            promise.resolve(resultMap);
        }
        else
        {
            promise.reject("Failed to call RCTCoreEthereumGasLimitRequest::getGas", "First parameter of RCTCoreEthereumGasLimitRequest::getGas should be an instance of RCTCoreEthereumGasLimitRequest");
        }
    }

    @ReactMethod
    public void getGasPrice(ReadableMap currentInstance, Promise promise)
    {
        String uid = currentInstance.getString("uid");
        if (uid.length() > 0)
        {
            EthereumGasLimitRequest javaObj = this.javaObjects.get(uid);
            String result = javaObj.getGasPrice();
            WritableNativeMap resultMap = new WritableNativeMap();
            resultMap.putString("value", result);
            promise.resolve(resultMap);
        }
        else
        {
            promise.reject("Failed to call RCTCoreEthereumGasLimitRequest::getGasPrice", "First parameter of RCTCoreEthereumGasLimitRequest::getGasPrice should be an instance of RCTCoreEthereumGasLimitRequest");
        }
    }

    @ReactMethod
    public void getAmplifier(ReadableMap currentInstance, Promise promise)
    {
        String uid = currentInstance.getString("uid");
        if (uid.length() > 0)
        {
            EthereumGasLimitRequest javaObj = this.javaObjects.get(uid);
            String result = javaObj.getAmplifier();
            WritableNativeMap resultMap = new WritableNativeMap();
            resultMap.putString("value", result);
            promise.resolve(resultMap);
        }
        else
        {
            promise.reject("Failed to call RCTCoreEthereumGasLimitRequest::getAmplifier", "First parameter of RCTCoreEthereumGasLimitRequest::getAmplifier should be an instance of RCTCoreEthereumGasLimitRequest");
        }
    }

}
