// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from core.djinni

package com.ledger.reactnative;

import co.ledger.core.DurationMetric;
import co.ledger.core.DurationMetrics;
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.bridge.ReadableArray;
import com.facebook.react.bridge.ReadableMap;
import com.facebook.react.bridge.ReadableNativeArray;
import com.facebook.react.bridge.ReadableNativeMap;
import com.facebook.react.bridge.WritableNativeArray;
import com.facebook.react.bridge.WritableNativeMap;
import com.facebook.react.module.annotations.ReactModule;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Optional;
import java.util.TimeZone;
import java.util.UUID;

@ReactModule(name = "RCTCoreDurationMetrics")
public class RCTCoreDurationMetrics extends ReactContextBaseJavaModule {

    private final ReactApplicationContext reactContext;
    private Map<String, DurationMetrics> javaObjects;
    public Map<String, DurationMetrics> getJavaObjects()
    {
        return javaObjects;
    }

    public RCTCoreDurationMetrics(ReactApplicationContext reactContext)
    {
        super(reactContext);
        this.reactContext = reactContext;
        this.javaObjects = new HashMap<String, DurationMetrics>();
    }

    @Override
    public String getName()
    {
        return "RCTCoreDurationMetrics";
    }
    @ReactMethod
    public void release(ReadableMap currentInstance, Promise promise)
    {
        String uid = currentInstance.getString("uid");
        if (uid.length() > 0)
        {
            this.javaObjects.remove(uid);
            promise.resolve(0);
        }
        else
        {
            promise.reject("Failed to release instance of RCTCoreDurationMetrics", "First parameter of RCTCoreDurationMetrics::release should be an instance of RCTCoreDurationMetrics");
        }
    }
    @ReactMethod
    public void log(Promise promise)
    {
        WritableNativeArray result = new WritableNativeArray();
        for (Map.Entry<String, DurationMetrics> elem : this.javaObjects.entrySet())
        {
            result.pushString(elem.getKey());
        }
        promise.resolve(result);
    }
    @ReactMethod
    public void flush(Promise promise)
    {
        this.javaObjects.clear();
        promise.resolve(0);
    }
    @ReactMethod
    public void isNull(ReadableMap currentInstance, Promise promise)
    {
        String uid = currentInstance.getString("uid");
        if (uid.length() > 0)
        {
            if (this.javaObjects.get(uid) == null)
            {
                promise.resolve(true);
                return;
            }
            else
            {
                promise.resolve(false);
                return;
            }
        }
        promise.resolve(true);
    }

    /** Get all duration metrics */
    @ReactMethod
    public void getAllDurationMetrics(Promise promise) {
        try
        {
            HashMap<String, DurationMetric> javaResult = DurationMetrics.getAllDurationMetrics();
            WritableNativeMap result = new WritableNativeMap();
            WritableNativeMap javaResult_map = new WritableNativeMap();
            for(String javaResult_key : javaResult.keySet())
            {
                DurationMetric javaResult_elem_value = javaResult.get(javaResult_key);
                javaResult_map.putString(javaResult_key, javaResult_elem_value);
            }
            result.putMap("value", javaResult_map);

            promise.resolve(result);
        }
        catch(Exception e)
        {
            promise.reject(e.toString(), e.getMessage());
        }
    }
}
