// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from addresses.djinni

package com.ledger.reactnative;

import co.ledger.core.CosmosLikeNetworkParameters;
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.bridge.ReadableArray;
import com.facebook.react.bridge.ReadableMap;
import com.facebook.react.bridge.ReadableNativeArray;
import com.facebook.react.bridge.ReadableNativeMap;
import com.facebook.react.bridge.WritableNativeArray;
import com.facebook.react.bridge.WritableNativeMap;
import com.facebook.react.module.annotations.ReactModule;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Optional;
import java.util.TimeZone;
import java.util.UUID;

@ReactModule(name = "RCTCoreCosmosLikeNetworkParameters")
public class RCTCoreCosmosLikeNetworkParameters extends ReactContextBaseJavaModule {
    private final ReactApplicationContext reactContext;
    private Map<String, CosmosLikeNetworkParameters> javaObjects;
    public Map<String, CosmosLikeNetworkParameters> getJavaObjects()
    {
        return javaObjects;
    }

    public RCTCoreCosmosLikeNetworkParameters(ReactApplicationContext reactContext)
    {
        super(reactContext);
        this.reactContext = reactContext;
        this.javaObjects = new HashMap<String, CosmosLikeNetworkParameters>();
    }

    @Override
    public String getName()
    {
        return "RCTCoreCosmosLikeNetworkParameters";
    }
    @ReactMethod
    public void release(ReadableMap currentInstance, Promise promise)
    {
        String uid = currentInstance.getString("uid");
        if (uid.length() > 0)
        {
            this.javaObjects.remove(uid);
            promise.resolve(0);
        }
        else
        {
            promise.reject("Failed to release instance of RCTCoreCosmosLikeNetworkParameters", "First parameter of RCTCoreCosmosLikeNetworkParameters::release should be an instance of RCTCoreCosmosLikeNetworkParameters");
        }
    }
    @ReactMethod
    public void log(Promise promise)
    {
        WritableNativeArray result = new WritableNativeArray();
        for (Map.Entry<String, CosmosLikeNetworkParameters> elem : this.javaObjects.entrySet())
        {
            result.pushString(elem.getKey());
        }
        promise.resolve(result);
    }
    @ReactMethod
    public void flush(Promise promise)
    {
        this.javaObjects.clear();
        promise.resolve(0);
    }
    @ReactMethod
    public void isNull(ReadableMap currentInstance, Promise promise)
    {
        String uid = currentInstance.getString("uid");
        if (uid.length() > 0)
        {
            if (this.javaObjects.get(uid) == null)
            {
                promise.resolve(true);
                return;
            }
            else
            {
                promise.resolve(false);
                return;
            }
        }
        promise.resolve(true);
    }
    public static byte[] hexStringToByteArray(String hexString)
    {
        int hexStringLength = hexString.length();
        byte[] data = new byte[hexStringLength / 2];
        for (int i = 0; i < hexStringLength; i += 2)
        {
            data[i / 2] = (byte) ((Character.digit(hexString.charAt(i), 16) << 4) + Character.digit(hexString.charAt(i+1), 16));
        }
        return data;
    }
    static final String HEXES = "0123456789ABCDEF";
    public static String byteArrayToHexString( byte [] data)
    {
        if (data == null)
        {
            return null;
        }
        final StringBuilder hexStringBuilder = new StringBuilder( 2 * data.length );
        for ( final byte b : data )
        {
            hexStringBuilder.append(HEXES.charAt((b & 0xF0) >> 4)).append(HEXES.charAt((b & 0x0F)));
        }
        return hexStringBuilder.toString();
    }

    @ReactMethod
    public void init(String Identifier, String MessagePrefix, String XPUBVersion, String PubKeyPrefix, String Ed25519PubKeyPrefix, String AddressPrefix, String ChainId, ReadableArray AdditionalCIPs, Promise promise) {
        byte [] javaParam_2 = hexStringToByteArray(XPUBVersion);

        byte [] javaParam_3 = hexStringToByteArray(PubKeyPrefix);

        byte [] javaParam_4 = hexStringToByteArray(Ed25519PubKeyPrefix);

        byte [] javaParam_5 = hexStringToByteArray(AddressPrefix);

        ArrayList<String> javaParam_7 = new ArrayList<String>();
        for (int i = 0; i <  AdditionalCIPs.size(); i++)
        {
            String AdditionalCIPs_elem = AdditionalCIPs.getString(i);
            javaParam_7.add(AdditionalCIPs_elem);
        }
        CosmosLikeNetworkParameters javaResult = new CosmosLikeNetworkParameters(Identifier, MessagePrefix, javaParam_2, javaParam_3, javaParam_4, javaParam_5, ChainId, javaParam_7);

        String uuid = UUID.randomUUID().toString();
        this.javaObjects.put(uuid, javaResult);
        WritableNativeMap finalResult = new WritableNativeMap();
        finalResult.putString("type","RCTCoreCosmosLikeNetworkParameters");
        finalResult.putString("uid",uuid);
        promise.resolve(finalResult);
    }
    @ReactMethod
    public void getIdentifier(ReadableMap currentInstance, Promise promise)
    {
        String uid = currentInstance.getString("uid");
        if (uid.length() > 0)
        {
            CosmosLikeNetworkParameters javaObj = this.javaObjects.get(uid);
            String result = javaObj.getIdentifier();
            WritableNativeMap resultMap = new WritableNativeMap();
            resultMap.putString("value", result);
            promise.resolve(resultMap);
        }
        else
        {
            promise.reject("Failed to call RCTCoreCosmosLikeNetworkParameters::getIdentifier", "First parameter of RCTCoreCosmosLikeNetworkParameters::getIdentifier should be an instance of RCTCoreCosmosLikeNetworkParameters");
        }
    }

    @ReactMethod
    public void getMessagePrefix(ReadableMap currentInstance, Promise promise)
    {
        String uid = currentInstance.getString("uid");
        if (uid.length() > 0)
        {
            CosmosLikeNetworkParameters javaObj = this.javaObjects.get(uid);
            String result = javaObj.getMessagePrefix();
            WritableNativeMap resultMap = new WritableNativeMap();
            resultMap.putString("value", result);
            promise.resolve(resultMap);
        }
        else
        {
            promise.reject("Failed to call RCTCoreCosmosLikeNetworkParameters::getMessagePrefix", "First parameter of RCTCoreCosmosLikeNetworkParameters::getMessagePrefix should be an instance of RCTCoreCosmosLikeNetworkParameters");
        }
    }

    @ReactMethod
    public void getXPUBVersion(ReadableMap currentInstance, Promise promise)
    {
        String uid = currentInstance.getString("uid");
        if (uid.length() > 0)
        {
            CosmosLikeNetworkParameters javaObj = this.javaObjects.get(uid);
            byte[] result = javaObj.getXPUBVersion();
            String converted_result = byteArrayToHexString(result);
            WritableNativeMap resultMap = new WritableNativeMap();
            resultMap.putString("value", converted_result);
            promise.resolve(resultMap);
        }
        else
        {
            promise.reject("Failed to call RCTCoreCosmosLikeNetworkParameters::getXPUBVersion", "First parameter of RCTCoreCosmosLikeNetworkParameters::getXPUBVersion should be an instance of RCTCoreCosmosLikeNetworkParameters");
        }
    }

    @ReactMethod
    public void getPubKeyPrefix(ReadableMap currentInstance, Promise promise)
    {
        String uid = currentInstance.getString("uid");
        if (uid.length() > 0)
        {
            CosmosLikeNetworkParameters javaObj = this.javaObjects.get(uid);
            byte[] result = javaObj.getPubKeyPrefix();
            String converted_result = byteArrayToHexString(result);
            WritableNativeMap resultMap = new WritableNativeMap();
            resultMap.putString("value", converted_result);
            promise.resolve(resultMap);
        }
        else
        {
            promise.reject("Failed to call RCTCoreCosmosLikeNetworkParameters::getPubKeyPrefix", "First parameter of RCTCoreCosmosLikeNetworkParameters::getPubKeyPrefix should be an instance of RCTCoreCosmosLikeNetworkParameters");
        }
    }

    @ReactMethod
    public void getEd25519PubKeyPrefix(ReadableMap currentInstance, Promise promise)
    {
        String uid = currentInstance.getString("uid");
        if (uid.length() > 0)
        {
            CosmosLikeNetworkParameters javaObj = this.javaObjects.get(uid);
            byte[] result = javaObj.getEd25519PubKeyPrefix();
            String converted_result = byteArrayToHexString(result);
            WritableNativeMap resultMap = new WritableNativeMap();
            resultMap.putString("value", converted_result);
            promise.resolve(resultMap);
        }
        else
        {
            promise.reject("Failed to call RCTCoreCosmosLikeNetworkParameters::getEd25519PubKeyPrefix", "First parameter of RCTCoreCosmosLikeNetworkParameters::getEd25519PubKeyPrefix should be an instance of RCTCoreCosmosLikeNetworkParameters");
        }
    }

    @ReactMethod
    public void getAddressPrefix(ReadableMap currentInstance, Promise promise)
    {
        String uid = currentInstance.getString("uid");
        if (uid.length() > 0)
        {
            CosmosLikeNetworkParameters javaObj = this.javaObjects.get(uid);
            byte[] result = javaObj.getAddressPrefix();
            String converted_result = byteArrayToHexString(result);
            WritableNativeMap resultMap = new WritableNativeMap();
            resultMap.putString("value", converted_result);
            promise.resolve(resultMap);
        }
        else
        {
            promise.reject("Failed to call RCTCoreCosmosLikeNetworkParameters::getAddressPrefix", "First parameter of RCTCoreCosmosLikeNetworkParameters::getAddressPrefix should be an instance of RCTCoreCosmosLikeNetworkParameters");
        }
    }

    @ReactMethod
    public void getChainId(ReadableMap currentInstance, Promise promise)
    {
        String uid = currentInstance.getString("uid");
        if (uid.length() > 0)
        {
            CosmosLikeNetworkParameters javaObj = this.javaObjects.get(uid);
            String result = javaObj.getChainId();
            WritableNativeMap resultMap = new WritableNativeMap();
            resultMap.putString("value", result);
            promise.resolve(resultMap);
        }
        else
        {
            promise.reject("Failed to call RCTCoreCosmosLikeNetworkParameters::getChainId", "First parameter of RCTCoreCosmosLikeNetworkParameters::getChainId should be an instance of RCTCoreCosmosLikeNetworkParameters");
        }
    }

    @ReactMethod
    public void getAdditionalCIPs(ReadableMap currentInstance, Promise promise)
    {
        String uid = currentInstance.getString("uid");
        if (uid.length() > 0)
        {
            CosmosLikeNetworkParameters javaObj = this.javaObjects.get(uid);
            ArrayList<String> result = javaObj.getAdditionalCIPs();
            WritableNativeArray converted_result = new WritableNativeArray();
            for (String result_elem : result)
            {
                converted_result.pushString(result_elem);
            }
            promise.resolve(converted_result);
        }
        else
        {
            promise.reject("Failed to call RCTCoreCosmosLikeNetworkParameters::getAdditionalCIPs", "First parameter of RCTCoreCosmosLikeNetworkParameters::getAdditionalCIPs should be an instance of RCTCoreCosmosLikeNetworkParameters");
        }
    }

}
