// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from addresses.djinni

package co.ledger.core;

/**
 * Strategy used to compute the dust.
 *
 * This basically gives the unit in which the dust will be expressed.
 */
public enum BitcoinLikeDustPolicy {
    FIXED,
    PER_BYTE,
    PER_KBYTE,
    ;
}
