// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

package co.ledger.core;

public final class CosmosLikeMsgWithdrawValidatorCommission {


    /*package*/ final String validatorAddress;

    public CosmosLikeMsgWithdrawValidatorCommission(
            String validatorAddress) {
        this.validatorAddress = validatorAddress;
    }

    public String getValidatorAddress() {
        return validatorAddress;
    }

    @Override
    public String toString() {
        return "CosmosLikeMsgWithdrawValidatorCommission{" +
                "validatorAddress=" + validatorAddress +
        "}";
    }

}
