// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

package co.ledger.core;

import java.util.ArrayList;

public final class CosmosLikeMsgDeposit {


    /*package*/ final String depositor;

    /*package*/ final String proposalId;

    /*package*/ final ArrayList<CosmosLikeAmount> amount;

    public CosmosLikeMsgDeposit(
            String depositor,
            String proposalId,
            ArrayList<CosmosLikeAmount> amount) {
        this.depositor = depositor;
        this.proposalId = proposalId;
        this.amount = amount;
    }

    public String getDepositor() {
        return depositor;
    }

    public String getProposalId() {
        return proposalId;
    }

    public ArrayList<CosmosLikeAmount> getAmount() {
        return amount;
    }

    @Override
    public String toString() {
        return "CosmosLikeMsgDeposit{" +
                "depositor=" + depositor +
                "," + "proposalId=" + proposalId +
                "," + "amount=" + amount +
        "}";
    }

}
