// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

package co.ledger.core;

/** Probably deprecated and replaced by MsgWithdrawDelegatIONReward */
public final class CosmosLikeMsgWithdrawDelegatorReward {


    /*package*/ final String delegatorAddress;

    /*package*/ final String validatorAddress;

    public CosmosLikeMsgWithdrawDelegatorReward(
            String delegatorAddress,
            String validatorAddress) {
        this.delegatorAddress = delegatorAddress;
        this.validatorAddress = validatorAddress;
    }

    public String getDelegatorAddress() {
        return delegatorAddress;
    }

    public String getValidatorAddress() {
        return validatorAddress;
    }

    @Override
    public String toString() {
        return "CosmosLikeMsgWithdrawDelegatorReward{" +
                "delegatorAddress=" + delegatorAddress +
                "," + "validatorAddress=" + validatorAddress +
        "}";
    }

}
