// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ethereum_like_wallet.djinni

package co.ledger.core;

import java.util.ArrayList;
import java.util.concurrent.atomic.AtomicBoolean;

/**Class representing a Ethereum account */
public abstract class EthereumLikeAccount {
    public abstract void broadcastRawTransaction(byte[] transaction, StringCallback callback);

    public abstract void broadcastTransaction(EthereumLikeTransaction transaction, StringCallback callback);

    public abstract EthereumLikeTransactionBuilder buildTransaction();

    public abstract ArrayList<ERC20LikeAccount> getERC20Accounts();

    private static final class CppProxy extends EthereumLikeAccount
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public void broadcastRawTransaction(byte[] transaction, StringCallback callback)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_broadcastRawTransaction(this.nativeRef, transaction, callback);
        }
        private native void native_broadcastRawTransaction(long _nativeRef, byte[] transaction, StringCallback callback);

        @Override
        public void broadcastTransaction(EthereumLikeTransaction transaction, StringCallback callback)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_broadcastTransaction(this.nativeRef, transaction, callback);
        }
        private native void native_broadcastTransaction(long _nativeRef, EthereumLikeTransaction transaction, StringCallback callback);

        @Override
        public EthereumLikeTransactionBuilder buildTransaction()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_buildTransaction(this.nativeRef);
        }
        private native EthereumLikeTransactionBuilder native_buildTransaction(long _nativeRef);

        @Override
        public ArrayList<ERC20LikeAccount> getERC20Accounts()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getERC20Accounts(this.nativeRef);
        }
        private native ArrayList<ERC20LikeAccount> native_getERC20Accounts(long _nativeRef);
    }
}
