// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ethereum_like_wallet.djinni

package co.ledger.core;

import java.util.ArrayList;
import java.util.concurrent.atomic.AtomicBoolean;

/** Class representing a Ethereum Operation. */
public abstract class EthereumLikeOperation {
    /**
     * Get operation's transaction.
     * @return EthereumLikeTransaction object
     */
    public abstract EthereumLikeTransaction getTransaction();

    /** Get all actions triggered by this transaction */
    public abstract ArrayList<InternalTransaction> getInternalTransactions();
    /** Release the underlying native object */
    public abstract void destroy();


    private static final class CppProxy extends EthereumLikeOperation
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        @Override
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public EthereumLikeTransaction getTransaction()
        {
            if (this.destroyed.get())
            {
                throw new RuntimeException("trying to use a destroyed object (EthereumLikeOperation)");
            }
            return native_getTransaction(this.nativeRef);
        }
        private native EthereumLikeTransaction native_getTransaction(long _nativeRef);

        @Override
        public ArrayList<InternalTransaction> getInternalTransactions()
        {
            if (this.destroyed.get())
            {
                throw new RuntimeException("trying to use a destroyed object (EthereumLikeOperation)");
            }
            return native_getInternalTransactions(this.nativeRef);
        }
        private native ArrayList<InternalTransaction> native_getInternalTransactions(long _nativeRef);
    }
}
