// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ethereum_like_wallet.djinni

package co.ledger.core;

import java.util.concurrent.atomic.AtomicBoolean;

/** Class representing an Ethereum internal transaction. */
public abstract class InternalTransaction {
    /** Get start gas (in wei) : maximum amount of gas the originator is willing to pay. */
    public abstract BigInt getGasLimit();

    /** Used gas (in wei) : used gas during this transaction: */
    public abstract BigInt getUsedGas();

    /** Get source ETH address. */
    public abstract String getSender();

    /** Get destination ETH address. */
    public abstract String getReceiver();

    /** Get amount of ether to send. */
    public abstract BigInt getValue();

    /** Get binary data payload. */
    public abstract byte[] getData();

    /** Get operation type : whether it is a SEND or RECEIVE. */
    public abstract OperationType getOperationType();

    private static final class CppProxy extends InternalTransaction
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public BigInt getGasLimit()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getGasLimit(this.nativeRef);
        }
        private native BigInt native_getGasLimit(long _nativeRef);

        @Override
        public BigInt getUsedGas()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getUsedGas(this.nativeRef);
        }
        private native BigInt native_getUsedGas(long _nativeRef);

        @Override
        public String getSender()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getSender(this.nativeRef);
        }
        private native String native_getSender(long _nativeRef);

        @Override
        public String getReceiver()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getReceiver(this.nativeRef);
        }
        private native String native_getReceiver(long _nativeRef);

        @Override
        public BigInt getValue()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getValue(this.nativeRef);
        }
        private native BigInt native_getValue(long _nativeRef);

        @Override
        public byte[] getData()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getData(this.nativeRef);
        }
        private native byte[] native_getData(long _nativeRef);

        @Override
        public OperationType getOperationType()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getOperationType(this.nativeRef);
        }
        private native OperationType native_getOperationType(long _nativeRef);
    }
}
