// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from networks.djinni

package co.ledger.core;

import java.util.concurrent.atomic.AtomicBoolean;

/** All available blockchain networks parameters. */
public abstract class Networks {
    /** The Bitcoin network parameters. */
    public static native BitcoinLikeNetworkParameters bitcoin();

    /** The Ethereum network parameters. */
    public static native EthereumLikeNetworkParameters ethereum();

    /** The Ripple network parameters. */
    public static native RippleLikeNetworkParameters ripple();

    private static final class CppProxy extends Networks
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }
    }
}
