// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wallet.djinni

package co.ledger.core;

/**
 * Type of operation.
 *
 * It’s possible to either send funds or receive ones.
 */
public enum OperationType {
    SEND,
    RECEIVE,
    NONE,
    ;
}
