// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from idl.djinni

#import "LGAlgorandAssetTransferInfo.h"
#include "AlgorandAssetTransferInfo.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class LGAlgorandAssetTransferInfo;

namespace djinni_generated {

struct AlgorandAssetTransferInfo
{
    using CppType = ::ledger::core::api::AlgorandAssetTransferInfo;
    using ObjcType = LGAlgorandAssetTransferInfo*;

    using Boxed = AlgorandAssetTransferInfo;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
