// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from configuration.djinni

#import "LGAlgorandBlockchainObserverEngines+Private.h"
#import "LGAlgorandBlockchainObserverEngines.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface LGAlgorandBlockchainObserverEngines ()

- (id)initWithCpp:(const std::shared_ptr<::ledger::core::api::AlgorandBlockchainObserverEngines>&)cppRef;

@end

@implementation LGAlgorandBlockchainObserverEngines {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::ledger::core::api::AlgorandBlockchainObserverEngines>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::ledger::core::api::AlgorandBlockchainObserverEngines>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}


namespace djinni_generated {

auto AlgorandBlockchainObserverEngines::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto AlgorandBlockchainObserverEngines::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<LGAlgorandBlockchainObserverEngines>(cpp);
}

}  // namespace djinni_generated

@end
