// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from callback.djinni

#include "BoolCallback.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol LGBoolCallback;

namespace djinni_generated {

class BoolCallback
{
public:
    using CppType = std::shared_ptr<::ledger::core::api::BoolCallback>;
    using CppOptType = std::shared_ptr<::ledger::core::api::BoolCallback>;
    using ObjcType = id<LGBoolCallback>;

    using Boxed = BoolCallback;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

