// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#import "LGCosmosLikeMsgWithdrawDelegatorReward.h"
#include "CosmosLikeMsgWithdrawDelegatorReward.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class LGCosmosLikeMsgWithdrawDelegatorReward;

namespace djinni_generated {

struct CosmosLikeMsgWithdrawDelegatorReward
{
    using CppType = ::ledger::core::api::CosmosLikeMsgWithdrawDelegatorReward;
    using ObjcType = LGCosmosLikeMsgWithdrawDelegatorReward*;

    using Boxed = CosmosLikeMsgWithdrawDelegatorReward;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
