// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#import "LGCosmosLikeMsgVote.h"
#include "CosmosLikeMsgVote.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class LGCosmosLikeMsgVote;

namespace djinni_generated {

struct CosmosLikeMsgVote
{
    using CppType = ::ledger::core::api::CosmosLikeMsgVote;
    using ObjcType = LGCosmosLikeMsgVote*;

    using Boxed = CosmosLikeMsgVote;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
