// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from database.djinni

#import "LGDatabaseResultRow+Private.h"
#import "LGDatabaseResultRow.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#import "LGDatabaseBlob+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class DatabaseResultRow::ObjcProxy final
: public ::ledger::core::api::DatabaseResultRow
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated::DatabaseResultRow;
public:
    using ObjcProxyBase::ObjcProxyBase;
    bool isNullAtPos(int32_t c_pos) override
    {
        @autoreleasepool {
            auto objcpp_result_ = [djinni_private_get_proxied_objc_object() isNullAtPos:(::djinni::I32::fromCpp(c_pos))];
            return ::djinni::Bool::toCpp(objcpp_result_);
        }
    }
    std::string getColumnName(int32_t c_pos) override
    {
        @autoreleasepool {
            auto objcpp_result_ = [djinni_private_get_proxied_objc_object() getColumnName:(::djinni::I32::fromCpp(c_pos))];
            return ::djinni::String::toCpp(objcpp_result_);
        }
    }
    int16_t getShortByPos(int32_t c_pos) override
    {
        @autoreleasepool {
            auto objcpp_result_ = [djinni_private_get_proxied_objc_object() getShortByPos:(::djinni::I32::fromCpp(c_pos))];
            return ::djinni::I16::toCpp(objcpp_result_);
        }
    }
    int32_t getIntByPos(int32_t c_pos) override
    {
        @autoreleasepool {
            auto objcpp_result_ = [djinni_private_get_proxied_objc_object() getIntByPos:(::djinni::I32::fromCpp(c_pos))];
            return ::djinni::I32::toCpp(objcpp_result_);
        }
    }
    float getFloatByPos(int32_t c_pos) override
    {
        @autoreleasepool {
            auto objcpp_result_ = [djinni_private_get_proxied_objc_object() getFloatByPos:(::djinni::I32::fromCpp(c_pos))];
            return ::djinni::F32::toCpp(objcpp_result_);
        }
    }
    double getDoubleByPos(int32_t c_pos) override
    {
        @autoreleasepool {
            auto objcpp_result_ = [djinni_private_get_proxied_objc_object() getDoubleByPos:(::djinni::I32::fromCpp(c_pos))];
            return ::djinni::F64::toCpp(objcpp_result_);
        }
    }
    int64_t getLongByPos(int32_t c_pos) override
    {
        @autoreleasepool {
            auto objcpp_result_ = [djinni_private_get_proxied_objc_object() getLongByPos:(::djinni::I32::fromCpp(c_pos))];
            return ::djinni::I64::toCpp(objcpp_result_);
        }
    }
    std::string getStringByPos(int32_t c_pos) override
    {
        @autoreleasepool {
            auto objcpp_result_ = [djinni_private_get_proxied_objc_object() getStringByPos:(::djinni::I32::fromCpp(c_pos))];
            return ::djinni::String::toCpp(objcpp_result_);
        }
    }
    std::shared_ptr<::ledger::core::api::DatabaseBlob> getBlobByPos(int32_t c_pos) override
    {
        @autoreleasepool {
            auto objcpp_result_ = [djinni_private_get_proxied_objc_object() getBlobByPos:(::djinni::I32::fromCpp(c_pos))];
            return ::djinni_generated::DatabaseBlob::toCpp(objcpp_result_);
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto DatabaseResultRow::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto DatabaseResultRow::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).djinni_private_get_proxied_objc_object();
}

}  // namespace djinni_generated
