// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ethereum_like_wallet.djinni

#import "LGEthereumGasLimitRequest+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto EthereumGasLimitRequest::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.from),
            ::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.to),
            ::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.value),
            ::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.data),
            ::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.gas),
            ::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.gasPrice),
            ::djinni::Optional<std::experimental::optional, ::djinni::F64>::toCpp(obj.amplifier)};
}

auto EthereumGasLimitRequest::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[LGEthereumGasLimitRequest alloc] initWithFrom:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.from))
                                                        to:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.to))
                                                     value:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.value))
                                                      data:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.data))
                                                       gas:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.gas))
                                                  gasPrice:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.gasPrice))
                                                 amplifier:(::djinni::Optional<std::experimental::optional, ::djinni::F64>::fromCpp(cpp.amplifier))];
}

}  // namespace djinni_generated
