// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from addresses.djinni

#import "LGEthereumLikeNetworkParameters.h"
#include "EthereumLikeNetworkParameters.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class LGEthereumLikeNetworkParameters;

namespace djinni_generated {

struct EthereumLikeNetworkParameters
{
    using CppType = ::ledger::core::api::EthereumLikeNetworkParameters;
    using ObjcType = LGEthereumLikeNetworkParameters*;

    using Boxed = EthereumLikeNetworkParameters;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
