// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ripple_like_wallet.djinni

#include "RippleLikeAccount.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class LGRippleLikeAccount;

namespace djinni_generated {

class RippleLikeAccount
{
public:
    using CppType = std::shared_ptr<::ledger::core::api::RippleLikeAccount>;
    using CppOptType = std::shared_ptr<::ledger::core::api::RippleLikeAccount>;
    using ObjcType = LGRippleLikeAccount*;

    using Boxed = RippleLikeAccount;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

