// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from addresses.djinni

#include "StellarLikeAddress.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class LGStellarLikeAddress;

namespace djinni_generated {

class StellarLikeAddress
{
public:
    using CppType = std::shared_ptr<::ledger::core::api::StellarLikeAddress>;
    using CppOptType = std::shared_ptr<::ledger::core::api::StellarLikeAddress>;
    using ObjcType = LGStellarLikeAddress*;

    using Boxed = StellarLikeAddress;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

