// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from tezos_like_wallet.djinni

#import "LGTezosLikeAccount+Private.h"
#import "LGTezosLikeAccount.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#import "LGBigIntCallback+Private.h"
#import "LGStringCallback+Private.h"
#import "LGTezosLikeOriginatedAccount+Private.h"
#import "LGTezosLikeTransaction+Private.h"
#import "LGTezosLikeTransactionBuilder+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface LGTezosLikeAccount ()

- (id)initWithCpp:(const std::shared_ptr<::ledger::core::api::TezosLikeAccount>&)cppRef;

@end

@implementation LGTezosLikeAccount {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::ledger::core::api::TezosLikeAccount>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::ledger::core::api::TezosLikeAccount>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (void)broadcastRawTransaction:(nonnull NSData *)transaction
                       callback:(nullable id<LGStringCallback>)callback {
    try {
        _cppRefHandle.get()->broadcastRawTransaction(::djinni::Binary::toCpp(transaction),
                                                     ::djinni_generated::StringCallback::toCpp(callback));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)broadcastTransaction:(nullable LGTezosLikeTransaction *)transaction
                    callback:(nullable id<LGStringCallback>)callback {
    try {
        _cppRefHandle.get()->broadcastTransaction(::djinni_generated::TezosLikeTransaction::toCpp(transaction),
                                                  ::djinni_generated::StringCallback::toCpp(callback));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nullable LGTezosLikeTransactionBuilder *)buildTransaction {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->buildTransaction();
        return ::djinni_generated::TezosLikeTransactionBuilder::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)getStorage:(nonnull NSString *)address
          callback:(nullable id<LGBigIntCallback>)callback {
    try {
        _cppRefHandle.get()->getStorage(::djinni::String::toCpp(address),
                                        ::djinni_generated::BigIntCallback::toCpp(callback));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)getEstimatedGasLimit:(nonnull NSString *)address
                    callback:(nullable id<LGBigIntCallback>)callback {
    try {
        _cppRefHandle.get()->getEstimatedGasLimit(::djinni::String::toCpp(address),
                                                  ::djinni_generated::BigIntCallback::toCpp(callback));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)getFees:(nullable id<LGBigIntCallback>)callback {
    try {
        _cppRefHandle.get()->getFees(::djinni_generated::BigIntCallback::toCpp(callback));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)getGasPrice:(nullable id<LGBigIntCallback>)callback {
    try {
        _cppRefHandle.get()->getGasPrice(::djinni_generated::BigIntCallback::toCpp(callback));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSArray<LGTezosLikeOriginatedAccount *> *)getOriginatedAccounts {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->getOriginatedAccounts();
        return ::djinni::List<::djinni_generated::TezosLikeOriginatedAccount>::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)getCurrentDelegate:(nullable id<LGStringCallback>)callback {
    try {
        _cppRefHandle.get()->getCurrentDelegate(::djinni_generated::StringCallback::toCpp(callback));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)getTokenBalance:(nonnull NSString *)tokenAddress
               callback:(nullable id<LGBigIntCallback>)callback {
    try {
        _cppRefHandle.get()->getTokenBalance(::djinni::String::toCpp(tokenAddress),
                                             ::djinni_generated::BigIntCallback::toCpp(callback));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto TezosLikeAccount::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto TezosLikeAccount::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<LGTezosLikeAccount>(cpp);
}

}  // namespace djinni_generated

@end
