// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from addresses.djinni

#import "LGTezosLikeNetworkParameters+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto TezosLikeNetworkParameters::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.Identifier),
            ::djinni::String::toCpp(obj.MessagePrefix),
            ::djinni::Binary::toCpp(obj.XPUBVersion),
            ::djinni::Binary::toCpp(obj.ImplicitPrefix),
            ::djinni::Binary::toCpp(obj.OriginatedPrefix),
            ::djinni::List<::djinni::String>::toCpp(obj.AdditionalTIPs),
            ::djinni::I64::toCpp(obj.TimestampDelay)};
}

auto TezosLikeNetworkParameters::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[LGTezosLikeNetworkParameters alloc] initWithIdentifier:(::djinni::String::fromCpp(cpp.Identifier))
                                                      MessagePrefix:(::djinni::String::fromCpp(cpp.MessagePrefix))
                                                        XPUBVersion:(::djinni::Binary::fromCpp(cpp.XPUBVersion))
                                                     ImplicitPrefix:(::djinni::Binary::fromCpp(cpp.ImplicitPrefix))
                                                   OriginatedPrefix:(::djinni::Binary::fromCpp(cpp.OriginatedPrefix))
                                                     AdditionalTIPs:(::djinni::List<::djinni::String>::fromCpp(cpp.AdditionalTIPs))
                                                     TimestampDelay:(::djinni::I64::fromCpp(cpp.TimestampDelay))];
}

}  // namespace djinni_generated
