// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from tezos_like_wallet.djinni

#import "LGBigIntCallback.h"
#import "LGStringCallback.h"
#import "LGTezosLikeAccount.h"
#import "LGTezosLikeOriginatedAccount.h"
#import "LGTezosLikeTransaction.h"
#import "LGTezosLikeTransactionBuilder.h"
#import "RCTCoreBaseModule.h"
#import "RCTCoreLGBigIntCallback.h"
#import "RCTCoreLGStringCallback.h"
#import "RCTCoreLGTezosLikeOriginatedAccount.h"
#import "RCTCoreLGTezosLikeTransaction.h"
#import "RCTCoreLGTezosLikeTransactionBuilder.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridge.h>
#import <React/RCTBridgeModule.h>


/**Class representing a Tezos account */
@interface RCTCoreLGTezosLikeAccount : RCTCoreBaseModule <RCTBridgeModule>
@end
