// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from tezos_like_wallet.djinni

#import "LGTezosConfigurationDefaults.h"
#import "RCTCoreBaseModule.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridge.h>
#import <React/RCTBridgeModule.h>


@interface RCTCoreLGTezosConfigurationDefaults : RCTCoreBaseModule <RCTBridgeModule>
@end
