// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from websocket_client.djinni

#import "LGErrorCode.h"
#import "LGWebSocketConnection.h"
#import "RCTCoreBaseModule.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridge.h>
#import <React/RCTBridgeModule.h>


/** A connection to a Web Socket. */
@interface RCTCoreLGWebSocketConnection : RCTCoreBaseModule <RCTBridgeModule>
@end
