// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ethereum_like_wallet.djinni

#import "LGAmount.h"
#import "LGEthereumLikeAddress.h"
#import "LGEthereumLikeBlock.h"
#import "LGEthereumLikeTransaction.h"
#import "RCTCoreBaseModule.h"
#import "RCTCoreLGAmount.h"
#import "RCTCoreLGEthereumLikeAddress.h"
#import "RCTCoreLGEthereumLikeBlock.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridge.h>
#import <React/RCTBridgeModule.h>


/** Class representing a Ethereum transaction. */
@interface RCTCoreLGEthereumLikeTransaction : RCTCoreBaseModule <RCTBridgeModule>
@end
