// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wallet.djinni

#import "LGAmount.h"
#import "LGCosmosLikeReward.h"
#import "RCTCoreBaseModule.h"
#import "RCTCoreLGAmount.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridge.h>
#import <React/RCTBridgeModule.h>


/**Class representing a Cosmos reward */
@interface RCTCoreLGCosmosLikeReward : RCTCoreBaseModule <RCTBridgeModule>
@end
