// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from addresses.djinni

#import "LGTezosLikeAddress.h"
#import "LGTezosLikeExtendedPublicKey.h"
#import "RCTCoreBaseModule.h"
#import "RCTCoreLGTezosLikeAddress.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridge.h>
#import <React/RCTBridgeModule.h>


/** The xPUB definition for Tezos. */
@interface RCTCoreLGTezosLikeExtendedPublicKey : RCTCoreBaseModule <RCTBridgeModule>
@end
