// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ripple_like_wallet.djinni

#import "LGRippleLikeAccount.h"
#import "LGRippleLikeTransaction.h"
#import "LGRippleLikeTransactionBuilder.h"
#import "LGStringCallback.h"
#import "RCTCoreBaseModule.h"
#import "RCTCoreLGRippleLikeTransaction.h"
#import "RCTCoreLGRippleLikeTransactionBuilder.h"
#import "RCTCoreLGStringCallback.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridge.h>
#import <React/RCTBridgeModule.h>


/**Class representing a Ripple account */
@interface RCTCoreLGRippleLikeAccount : RCTCoreBaseModule <RCTBridgeModule>
@end
