// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ripple_like_wallet.djinni

#import "LGAmount.h"
#import "LGBigInt.h"
#import "LGRippleLikeAddress.h"
#import "LGRippleLikeTransaction.h"
#import "RCTCoreBaseModule.h"
#import "RCTCoreLGAmount.h"
#import "RCTCoreLGBigInt.h"
#import "RCTCoreLGRippleLikeAddress.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridge.h>
#import <React/RCTBridgeModule.h>


/**
 * TODO: to be more accurate, all RippleLikeBlock classes should be renamed as RippleLikeLedger,
 * since there is an analogy between block and ledger concepts it's ok for the moment ...
 *Class representing a Ripple transaction
 */
@interface RCTCoreLGRippleLikeTransaction : RCTCoreBaseModule <RCTBridgeModule>
@end
