// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ripple_like_wallet.djinni

#import "LGRippleConfigurationDefaults.h"
#import "RCTCoreBaseModule.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridge.h>
#import <React/RCTBridgeModule.h>


@interface RCTCoreLGRippleConfigurationDefaults : RCTCoreBaseModule <RCTBridgeModule>
@end
