// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from configuration.djinni

#import "LGBlockchainExplorerEngines.h"
#import "RCTCoreBaseModule.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridge.h>
#import <React/RCTBridgeModule.h>


/** Available API to use with explorers. */
@interface RCTCoreLGBlockchainExplorerEngines : RCTCoreBaseModule <RCTBridgeModule>
@end
