// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from bitcoin_like_wallet.djinni

#import "Amount.h"
#import "BitcoinLikeOutput.h"
#import "BitcoinLikeScript.h"
#import "DerivationPath.h"
#import "RCTCoreAmount.h"
#import "RCTCoreBitcoinLikeScript.h"
#import "RCTCoreDerivationPath.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridge.h>
#import <React/RCTBridgeModule.h>


/**Class representing Bitcoin outputs */
@interface RCTCoreBitcoinLikeOutput : NSObject <RCTBridgeModule>
@property (nonatomic, strong) NSMutableDictionary *objcImplementations;
@end
