// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from bitcoin_like_wallet.djinni

#import "BitcoinLikeAccount.h"
#import "BitcoinLikeOutputListCallback.h"
#import "BitcoinLikeTransaction.h"
#import "BitcoinLikeTransactionBuilder.h"
#import "I32Callback.h"
#import "RCTCoreBitcoinLikeOutputListCallback.h"
#import "RCTCoreBitcoinLikeTransaction.h"
#import "RCTCoreBitcoinLikeTransactionBuilder.h"
#import "RCTCoreI32Callback.h"
#import "RCTCoreStringCallback.h"
#import "StringCallback.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridge.h>
#import <React/RCTBridgeModule.h>


/**Class representing a Bitcoin account */
@interface RCTCoreBitcoinLikeAccount : NSObject <RCTBridgeModule>
@property (nonatomic, strong) NSMutableDictionary *objcImplementations;
@end
