// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wallet.djinni

#import "OperationListCallback.h"
#import "OperationOrderKey.h"
#import "OperationQuery.h"
#import "QueryFilter.h"
#import "RCTCoreOperationListCallback.h"
#import "RCTCoreOperationQuery.h"
#import "RCTCoreQueryFilter.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridge.h>
#import <React/RCTBridgeModule.h>


/**Class respresenting a query for a set of operations */
@interface RCTCoreOperationQuery : NSObject <RCTBridgeModule>
@property (nonatomic, strong) NSMutableDictionary *objcImplementations;
@end
