// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http_client.djinni

#import "HttpClientImpl.h"
#import "HttpRequest.h"
#import "RCTCoreHttpRequest.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridge.h>
#import <React/RCTBridgeModule.h>


/**Class representing the http client performing the http requests */
@interface RCTCoreHttpClient : NSObject <RCTBridgeModule>
@property (nonatomic, strong) NSMutableDictionary *objcImplementations;
@end
